### ISSUE TITLE
Sprites don't always make it to their destination

### ISSUE THREAD

**Issue by zischwartz** [kittykatattack/charm#2]
It happens when enough frames don't elapse. 

This can happen due to a slow frame rate or a short duration, and especially in the case of both. 

The problem seems to be [this logic here](https://github.com/kittykatattack/charm/blob/master/src/charm.js#L147-L176).

**Comment by kittykatattack** [comment]
I've updated the repository with your fix.
Thanks so much for reporting and fixing this!! 👍

**Comment by zischwartz** [comment]
Glad I could help. Great tutorial and libraries by the way!
