### ISSUE TITLE
a totally es5 version

### ISSUE THREAD

**Issue by funkyLover** [kittykatattack/charm#3]
I need a totally es5 version, but I use `babel` to complie the src file can't get the result I want? I have tried  to config babel but dosen't work, maybe just miss some steps, please help me to get a totally es5 version😰

**Comment by kittykatattack** [comment]
Hi!
You'll find the ES5 version in the `bin` folder:

https://github.com/kittykatattack/charm/blob/master/bin/Charm.js

That should work :)
Yes, I know, Babel can be really difficult to configure.

**Comment by funkyLover** [comment]
um..nope, such as `Array.from(arr)` is the es6 syntax. I just make a webapp game within the webview in the android app `Wechat`,  the webview in `Wechat` get an custom-build kernel named `X5`, I think it is completely not support the `ES6`, poor indeed...So it is why I need `ES5` version..BTW, the [bump.js](https://github.com/kittykatattack/bump/blob/master/bin/bump.js#L1304) also get error with the `X5`, and it will work fine after i delete the code contain the `collision`

**Comment by funkyLover** [comment]
I find a ugly way finally, I use webpack + babel + babel+transform-runtime, to make a completely es5 version....and it work fine with Wechat's webview😭

**Comment by kittykatattack** [comment]
Oh wow!
That's impressive.
Webpack is no fun at all to configure, congratulations!
