### ISSUE TITLE
Problem with loops.

### ISSUE THREAD

**Issue by MCumic10** [kittykatattack/charm#5]
Hello, 

First time when I try to animate objects through a loop it works like a charm first time. Every other time only the last one gets animated. When I test same objects one by one animations work, Problem is only when I run it through loop. 

My code is simple:
`//this is loop
this.animateObjectArray = function() {
        for (var i = 0; i < this.toAnimateArray.length; i++) {
          playroom.utils.charm.fadeIn(toAnimateArray[i], 20);
        }
    } 

// and fadeIn f, c is charm object.
fadeIn: function(obj,time, to){
        if(obj.anim!= undefined){
          c.removeTween(obj.anim);
        }
        obj.visible = true;
        obj.anim = c.fadeIn(obj,time);
}`

Thanks in advance,
Milutin

**Comment by MCumic10** [comment]
Problem was in removeTween function. array.splice(-1,1) will always remove last elemnt of array.

So I changed removeTween to check if index of element to remove is != -1;

//Remove the tween if `tweenObject` doesn't have any nested
      //tween objects
      if (!tweenObject.tweens) {
        tweenObject.pause();
        if(this.globalTweens.indexOf(tweenObject)!= -1){ // this is new line
          this.globalTweens.splice(this.globalTweens.indexOf(tweenObject), 1);
        }
        //Otherwise, remove the nested tween objects
      }

**Comment by kittykatattack** [comment]
That's brilliant, thanks so much for debugging this!!

**Comment by kittykatattack** [comment]
@MCumic10 I've merged your fix - thanks again!
