### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by fredguest** [kittykatattack/charm#8]
Hey! This library and your Pixi.js guide are incredibly helpful, thank you. Have you considered publishing Charm to https://www.npmjs.com/ so people can `npm install charm`?

**Comment by kittykatattack** [comment]
Yes, please see here:

https://github.com/kittykatattack/hexi/issues/32

We would love some help! 😄

**Comment by fredguest** [comment]
Oh that's awesome! Excited to hear the project has legs 🤘🏼.
